#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories.LinqToSqlData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="usda_nutrient")]
	public partial class DbClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFoodDescrption(FoodDescrption instance);
    partial void UpdateFoodDescrption(FoodDescrption instance);
    partial void DeleteFoodDescrption(FoodDescrption instance);
    #endregion
		
		public DbClassesDataContext() : 
				base(global::Repositories.Properties.Settings.Default.usda_nutrientConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FoodDescrption> FoodDescrptions
		{
			get
			{
				return this.GetTable<FoodDescrption>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usda_food_des")]
	public partial class FoodDescrption : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id;
		
		private decimal _FdGrp_Cd;
		
		private string _Long_Desc;
		
		private string _Shrt_Desc;
		
		private string _ComName;
		
		private string _ManufacName;
		
		private string _Survey;
		
		private string _Ref_desc;
		
		private System.Nullable<decimal> _Refuse;
		
		private string _SciName;
		
		private System.Nullable<decimal> _N_Factor;
		
		private System.Nullable<decimal> _Pro_Factor;
		
		private System.Nullable<decimal> _Fat_Factor;
		
		private System.Nullable<decimal> _CHO_Factor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnFdGrp_CdChanging(decimal value);
    partial void OnFdGrp_CdChanged();
    partial void OnLong_DescChanging(string value);
    partial void OnLong_DescChanged();
    partial void OnShrt_DescChanging(string value);
    partial void OnShrt_DescChanged();
    partial void OnComNameChanging(string value);
    partial void OnComNameChanged();
    partial void OnManufacNameChanging(string value);
    partial void OnManufacNameChanged();
    partial void OnSurveyChanging(string value);
    partial void OnSurveyChanged();
    partial void OnRef_descChanging(string value);
    partial void OnRef_descChanged();
    partial void OnRefuseChanging(System.Nullable<decimal> value);
    partial void OnRefuseChanged();
    partial void OnSciNameChanging(string value);
    partial void OnSciNameChanged();
    partial void OnN_FactorChanging(System.Nullable<decimal> value);
    partial void OnN_FactorChanged();
    partial void OnPro_FactorChanging(System.Nullable<decimal> value);
    partial void OnPro_FactorChanged();
    partial void OnFat_FactorChanging(System.Nullable<decimal> value);
    partial void OnFat_FactorChanged();
    partial void OnCHO_FactorChanging(System.Nullable<decimal> value);
    partial void OnCHO_FactorChanged();
    #endregion
		
		public FoodDescrption()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="NDB_No", Storage="_Id", DbType="Decimal(5,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FdGrp_Cd", DbType="Decimal(4,0) NOT NULL")]
		public decimal FdGrp_Cd
		{
			get
			{
				return this._FdGrp_Cd;
			}
			set
			{
				if ((this._FdGrp_Cd != value))
				{
					this.OnFdGrp_CdChanging(value);
					this.SendPropertyChanging();
					this._FdGrp_Cd = value;
					this.SendPropertyChanged("FdGrp_Cd");
					this.OnFdGrp_CdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Long_Desc", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Long_Desc
		{
			get
			{
				return this._Long_Desc;
			}
			set
			{
				if ((this._Long_Desc != value))
				{
					this.OnLong_DescChanging(value);
					this.SendPropertyChanging();
					this._Long_Desc = value;
					this.SendPropertyChanged("Long_Desc");
					this.OnLong_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shrt_Desc", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Shrt_Desc
		{
			get
			{
				return this._Shrt_Desc;
			}
			set
			{
				if ((this._Shrt_Desc != value))
				{
					this.OnShrt_DescChanging(value);
					this.SendPropertyChanging();
					this._Shrt_Desc = value;
					this.SendPropertyChanged("Shrt_Desc");
					this.OnShrt_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComName", DbType="NVarChar(100)")]
		public string ComName
		{
			get
			{
				return this._ComName;
			}
			set
			{
				if ((this._ComName != value))
				{
					this.OnComNameChanging(value);
					this.SendPropertyChanging();
					this._ComName = value;
					this.SendPropertyChanged("ComName");
					this.OnComNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufacName", DbType="NVarChar(65)")]
		public string ManufacName
		{
			get
			{
				return this._ManufacName;
			}
			set
			{
				if ((this._ManufacName != value))
				{
					this.OnManufacNameChanging(value);
					this.SendPropertyChanging();
					this._ManufacName = value;
					this.SendPropertyChanged("ManufacName");
					this.OnManufacNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Survey", DbType="NVarChar(1)")]
		public string Survey
		{
			get
			{
				return this._Survey;
			}
			set
			{
				if ((this._Survey != value))
				{
					this.OnSurveyChanging(value);
					this.SendPropertyChanging();
					this._Survey = value;
					this.SendPropertyChanged("Survey");
					this.OnSurveyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ref_desc", DbType="NVarChar(135)")]
		public string Ref_desc
		{
			get
			{
				return this._Ref_desc;
			}
			set
			{
				if ((this._Ref_desc != value))
				{
					this.OnRef_descChanging(value);
					this.SendPropertyChanging();
					this._Ref_desc = value;
					this.SendPropertyChanged("Ref_desc");
					this.OnRef_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Refuse", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> Refuse
		{
			get
			{
				return this._Refuse;
			}
			set
			{
				if ((this._Refuse != value))
				{
					this.OnRefuseChanging(value);
					this.SendPropertyChanging();
					this._Refuse = value;
					this.SendPropertyChanged("Refuse");
					this.OnRefuseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SciName", DbType="NVarChar(65)")]
		public string SciName
		{
			get
			{
				return this._SciName;
			}
			set
			{
				if ((this._SciName != value))
				{
					this.OnSciNameChanging(value);
					this.SendPropertyChanging();
					this._SciName = value;
					this.SendPropertyChanged("SciName");
					this.OnSciNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Factor", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> N_Factor
		{
			get
			{
				return this._N_Factor;
			}
			set
			{
				if ((this._N_Factor != value))
				{
					this.OnN_FactorChanging(value);
					this.SendPropertyChanging();
					this._N_Factor = value;
					this.SendPropertyChanged("N_Factor");
					this.OnN_FactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Factor", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Pro_Factor
		{
			get
			{
				return this._Pro_Factor;
			}
			set
			{
				if ((this._Pro_Factor != value))
				{
					this.OnPro_FactorChanging(value);
					this.SendPropertyChanging();
					this._Pro_Factor = value;
					this.SendPropertyChanged("Pro_Factor");
					this.OnPro_FactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat_Factor", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Fat_Factor
		{
			get
			{
				return this._Fat_Factor;
			}
			set
			{
				if ((this._Fat_Factor != value))
				{
					this.OnFat_FactorChanging(value);
					this.SendPropertyChanging();
					this._Fat_Factor = value;
					this.SendPropertyChanged("Fat_Factor");
					this.OnFat_FactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHO_Factor", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> CHO_Factor
		{
			get
			{
				return this._CHO_Factor;
			}
			set
			{
				if ((this._CHO_Factor != value))
				{
					this.OnCHO_FactorChanging(value);
					this.SendPropertyChanging();
					this._CHO_Factor = value;
					this.SendPropertyChanged("CHO_Factor");
					this.OnCHO_FactorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
